import { pgTable, text, uuid, date, timestamp, pgEnum } from 'drizzle-orm/pg-core';
import { users } from './users.schema';
import { classSchedules } from './class-schedule.schema';
import { id } from './columns.helper';


// Class session status enum (different from live session status)
export const classSessionStatusEnum = pgEnum('class_session_status', [
  'scheduled',    // Terjadwal (generated, belum waktunya)
  'not_started',  // Belum dimulai (sudah waktunya tapi belum start)
  'in_progress',  // Sedang berlangsung (live)
  'completed',    // Selesai
  'cancelled',    // Dibatalkan
]);

// Class Session table - specific instance of a schedule on a specific date
// Generated by Admin/Administrative Employee
export const classSessions = pgTable('class_sessions', {
  ...id,

  // Reference to the recurring schedule
  scheduleId: uuid('schedule_id').references(() => classSchedules.id, { onDelete: 'cascade' }).notNull(),

  // The teacher who is assigned to this specific session
  teacherId: uuid('teacher_id').references(() => users.id, { onDelete: 'set null' }),

  // Session details
  date: date('date').notNull(), // The specific date of this session
  status: classSessionStatusEnum('status').default('scheduled').notNull(),

  // Actual times (may differ from scheduled times)
  actualStartTime: timestamp('actual_start_time'), // When teacher actually started
  actualEndTime: timestamp('actual_end_time'), // When session actually ended

  // Notes
  notes: text('notes'), // e.g., "Moved to Room 202 due to maintenance"
  cancellationReason: text('cancellation_reason'), // If cancelled

  // Audit - who generated/modified this session
  generatedBy: uuid('generated_by').references(() => users.id), // Admin/Staff who generated
  generatedAt: timestamp('generated_at').defaultNow().notNull(),
  startedBy: uuid('started_by').references(() => users.id), // Who clicked "Start"
  completedBy: uuid('completed_by').references(() => users.id), // Who clicked "End"
});

// Type exports
export type ClassSession = typeof classSessions.$inferSelect;
export type NewClassSession = typeof classSessions.$inferInsert;
