import { relations } from 'drizzle-orm';
import { classSchedules } from './class-schedule.schema';
import { classSessions } from './class-session.schema';
import { classAttendances } from './class-attendance.schema';
import { scheduleTeachers } from './schedule-teacher.schema';
import { users } from './users.schema';
import { classes } from './class.schema';

// Class Schedule relations
export const classSchedulesRelations = relations(classSchedules, ({ one, many }) => ({
  // A schedule belongs to one class
  class: one(classes, {
    fields: [classSchedules.classId],
    references: [classes.id],
  }),
  // A schedule has many teachers via junction table
  teachers: many(scheduleTeachers),
  // A schedule was created by one user
  createdByUser: one(users, {
    fields: [classSchedules.createdBy],
    references: [users.id],
    relationName: 'scheduleCreator',
  }),
  // A schedule has many sessions (instances)
  sessions: many(classSessions),
}));

// Class Session relations
export const classSessionsRelations = relations(classSessions, ({ one, many }) => ({
  // A session belongs to one schedule
  schedule: one(classSchedules, {
    fields: [classSessions.scheduleId],
    references: [classSchedules.id],
  }),
  // A session has one assigned teacher
  teacher: one(users, {
    fields: [classSessions.teacherId],
    references: [users.id],
    relationName: 'sessionTeacher',
  }),
  // A session was generated by one user
  generatedByUser: one(users, {
    fields: [classSessions.generatedBy],
    references: [users.id],
    relationName: 'sessionGenerator',
  }),
  // A session was started by one user
  startedByUser: one(users, {
    fields: [classSessions.startedBy],
    references: [users.id],
    relationName: 'sessionStarter',
  }),
  // A session was completed by one user
  completedByUser: one(users, {
    fields: [classSessions.completedBy],
    references: [users.id],
    relationName: 'sessionCompleter',
  }),
  // A session has many attendance records
  attendances: many(classAttendances),
}));

// Class Attendance relations
export const classAttendancesRelations = relations(classAttendances, ({ one }) => ({
  // An attendance record belongs to one session
  session: one(classSessions, {
    fields: [classAttendances.sessionId],
    references: [classSessions.id],
  }),
  // An attendance record belongs to one student
  student: one(users, {
    fields: [classAttendances.studentId],
    references: [users.id],
    relationName: 'attendanceStudent',
  }),
  // An attendance record was recorded by one user
  recordedByUser: one(users, {
    fields: [classAttendances.recordedBy],
    references: [users.id],
    relationName: 'attendanceRecorder',
  }),
}));
